### ISSUE TITLE
not displayed

### ISSUE THREAD

**Issue by mayerbalintdev** [fliegwerk/ssps#6]
Hi, I have a question. I programmed it but it doesn't work. The data.json looks like this but on the webpage you can't see anything but the logo.

{"password":"$2y$10$d2EVxpUJlZF93OH9iuwoGuN6u8uySTWH2cUvB0b7f7XPn6xhSUViG","states":{"operational":{"color":"Green","title":"Operational"},"upcoming-maintenance":{"color":"Blue","title":"Upcoming maintenance"},"under-maintenance":{"color":"Red","title":"Under maintenance"},"experiencing-issues":{"color":"Orange","title":"Experiencing issues"},"down":{"color":"Red","title":"Malfunction"}},"services":{"Website%0D":"Website\r","Api%0D":"Api\r","DNS":"DNS"},"entries":[]}

**Comment by pklaschka** [comment]
Hi! Just wanted to let you know I've seen the issue and will take a look at it in the new year.
